sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1

before_install:
  - gem install bundler -v 1.16.1
  - examples/ci-clear

bundler_args: --without production

env:
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1

before_script: examples/ci-put BUILDING REBUILDING

script: bundle exec rake knapsack:rspec && examples/ci-sync && examples/ci-deploy

after_success: examples/ci-post OK
after_failure: examples/ci-post FAILED
