sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.2

bundler_args: --without production

env:
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1

before_script: examples/ci-put BUILDING REBUILDING

script: bundle exec rake knapsack:rspec && examples/ci-sync && examples/ci-deploy

after_success: examples/ci-put OK
after_failure: examples/ci-put FAILED
