#!/usr/bin/env ruby
# frozen_string_literal: true

# Script that clears build status of
# travis nodes from synchronising service

require 'net/http'
require 'uri'
require 'json'

SLEEP_TIME_SECONDS = 30

env_ok = ENV['CI_NODE_INDEX'] &&
         ENV['CI_NODE_TOTAL'] &&
         ENV['IIDY_ENDPOINT'] &&
         ENV['TRAVIS_BUILD_NUMBER'] &&
         ENV['TRAVIS_JOB_NUMBER'] &&
         ENV['IIDY_TOKEN']

abort 'Bad env' unless env_ok

main_node = ENV['CI_NODE_INDEX'] == '0'
auth_token = "Token token=\"#{ENV['IIDY_TOKEN']}\""

if main_node
  build_id = "is_it_done_yet--#{ENV['TRAVIS_BUILD_NUMBER']}"

  url = ENV['IIDY_ENDPOINT'] + "/builds/#{build_id}"

  puts "URL: #{url}"

  uri = URI(url)

  request = Net::HTTP::Delete.new(uri)
  request['Authorization'] = auth_token

  response = Net::HTTP.start(
    uri.hostname,
    uri.port,
    use_ssl: uri.scheme == 'https'
  ) { |http| http.request(request) }

  abort 'Failed to clear results' unless response.code == '204'
  puts 'Successfully cleared results!'
else
  puts 'Not main node!'
end
